### ISSUE TITLE
Seminario1-revEdécio

### ISSUE THREAD

**Issue by edeciofernando** [Tibira/Goblin-s-Aid---Ajudante-de-Ficha-de-Personagem#2]
Sugestões:
- [x] Adicionar referências que justifiquem a criação do sistema (nº de jogadores de D&D 5e, crescimento deste tipo de game, ...)
- [x] Pensar em formas de obter retorno financeiro com o projeto e implementar no ER, casos de uso, etc.

**Comment by Tibira** [comment]
Bom dia professor.

Sugestões lidas, processadas e finalizadas, no dia da banca comentarei os resultados obtidos.

Abraços.
