### ISSUE TITLE
Seminário2-revEdécio

### ISSUE THREAD

**Issue by edeciofernando** [Tibira/Goblin-s-Aid---Ajudante-de-Ficha-de-Personagem#4]
Ok! De acordo com o esperado.
Parabéns pelas ações realizadas de entrar em contato com a empresa e verificar questões legais.

**Comment by Tibira** [comment]
Muito obrigado professor.

Fico feliz em estar de acordo com o esperado.

Obrigado pelos elogios :smile: 

Abraços.
