### ISSUE TITLE
Apresentação final de TCC I

### ISSUE THREAD

**Issue by Tibira** [Tibira/Goblin-s-Aid---Ajudante-de-Ficha-de-Personagem#5]
# Conteúdo da apresentação final:
- [x] Sistemas similares
- [x] Diagrama ER, Caso de Uso e Levantamento de Requisitos
- [x] Referências
- [x] Cronograma atualizado
- [x] Layout
- [x] CRUD
- [x] Hospedado

**Comment by Tibira** [comment]
Referencial teórico - falar sobre a industria do rpg, comentar sobre ferramentas similares e comparar com eles

**Comment by vinibacc** [comment]
Juntar referencial teórico com as referencias.
Adicionar descrição das principais tabelas.
Adicionar descrição dos atores.
Adicionar descrição na Introdução.
