### ISSUE TITLE
BancaFinal - revLuzzardi

### ISSUE THREAD

**Issue by pluzzardi** [Tibira/Goblin-s-Aid---Ajudante-de-Ficha-de-Personagem#6]
1. Sistemas similares, apenas um? Comparação com o sistema proposto (slide 7)

2. Banco de Dados Antecedentes - Profinci...

3. Preço 75 PO? Explicar as moedas

4. Objetivos Específicos: Aprofundar os conhecimentos em Laravel

**Comment by Tibira** [comment]
Resolvido os requisitos.

Quando o senhor estiver disponível gostaria de lhe mostrar para ver se o senhor aprova as mudanças.
