### ISSUE TITLE
BancaFinalTCCI - revEdécio

### ISSUE THREAD

**Issue by edeciofernando** [Tibira/Goblin-s-Aid---Ajudante-de-Ficha-de-Personagem#7]
Sugestões:
- [x] Acrescentar subtítulo indicativo dos objetivos do sistema
- [x] Descrever sobre as tecnologias e linguagens utilizadas (com referência) 
- [x] Ressaltar complexidade do sistema, além dos cadastros das fichas

**Comment by Tibira** [comment]
Resolvido os requisitos.

Quando o senhor estiver disponível gostaria de lhe mostrar para ver se o senhor aprova as mudanças.
