### ISSUE TITLE
Seminário1 - revLuzzardi

### ISSUE THREAD

**Issue by pluzzardi** [Tibira/Goblin-s-Aid---Ajudante-de-Ficha-de-Personagem#8]
1. Atualizar o E-R na Wiki, layout, cronograma, ... (atualizar toda a Wiki)
2. Corrigir as referências bibliográficas de internet (colocar no padrão)
3. Esperava ver codificação mais adiantada

**Comment by Tibira** [comment]
Boa tarde professor.

Crio ter correspondido a todos os requisitos do senhor.
